### ISSUE TITLE
ompile problem on linux using Mono

### ISSUE THREAD

**Issue by MartinMSPedersen** [VladimirReshetnikov/Oeis.A002845#1]
Would it be possible to modify the code so it can compile on Linux using mono?

I currently gets four errors because not the full C# 7.3 is supported.
<code>
$ mcs *cs
</code>
  * SparseInteger.Conversions.cs(11,5): error CS1644: Feature `readonly structs' cannot be used because it is not part of the C# 7.0 language specification

  * SparseInteger.cs(33,50): error CS1644: Feature `readonly structs' cannot be used because it is not part of the C# 7.0 language specification

  * SparseInteger.cs(63,59): error CS1644: Feature `default literal' cannot be used because it is not part of the C# 7.0 language specification

  * SparseInteger.cs(63,82): error CS1644: Feature `default literal' cannot be used because it is not part of the C# 7.0 language specification

**Compilation failed: 4 error(s), 0 warnings**

**Comment by KirillOsenkov** [comment]
@MartinMSPedersen what mono version are you using?

Try compiling using MSBuild and Csc (Roslyn C# compiler). 

Also try compiling with `-langversion:latest`.

**Comment by MartinMSPedersen** [comment]
OK. I manage to run it under CentOS linux using the guide at:
https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial
